### ISSUE TITLE
Recommend Ka-Block! for iOS

### ISSUE THREAD

**Issue by adidalal** [fivefilters/block-ads#11]
EDIT: I no longer recommend 1Blocker. See new comment below.

~~If you're looking to recommend something more powerful, I would recommend 1Blocker - https://1blocker.com. It actually has user-configurable blockers and uses the new Content Blocking APIs. Cons are, it's iOS9+ only (new APIs are available only on newer iOS versions, and 64-bit devices) and additional blocklists are a paid feature.~~

**Comment by fivefilters** [comment]
Thanks for the suggestion. Do you know what the difference is between the free and premium version? (Just additional blocklists?)

**Comment by adidalal** [comment]
Looks like: Multiple blocklists active at once, iOS Safari share sheet extension to quickly whitelist sites, custom rules, and iCloud sync. (and of course, supporting the developers)

**Comment by adidalal** [comment]
Did some research and trials, and I think Ka-Block! is a better suggestion, especially considering 1Blocker's newly announced product update.

Ka-Block is free and open source, and in my testing, seems to have a good set of filters.
http://kablock.com
https://github.com/dgraham/Ka-Block

**Comment by fivefilters** [comment]
Sorry for such a late reply.

Appreciate your suggestion here. We've reviewed this and a few more options and have decided to go with recommending [Better Blocker](https://better.fyi/). It seems to work well and we like the goals of the people behind it.
