### ISSUE TITLE
Add a note regarding potential false negatives and "killer" extensions

### ISSUE THREAD

**Issue by gparyani** [fivefilters/block-ads#14]
In addition to an ad blocker, I also use a "killer" extension when browsing the web; in other words, an extension that is designed to prevent websites from seeing that I have an ad blocker installed. This way, I can block ads on websites even if the site prevents me from being able to use my ad blocker.

It would be nice to add a section regarding potential reasons for false negatives (no ad blocker detected, but I do have one), which explains as one of the causes having a killer extension installed.

**Comment by fivefilters** [comment]
Sorry for the lack of a response.

The extensions you describe, unfortunately, are not very good at detecting ad-blocking *in general*. It's quite trivial for a site to detect ad-blocking as we do here. What those extension are good for is countering *specific* instances of ad-block detection, especially when sites do it to prevent visitors with ad-blockers from accessing content. 

Unfortunately some developers of these extensions want to try and stop any type of ad-block detection, regardless of intent. Now if that were possible, we'd be all for it, but it's not. We had a [long discussion](https://github.com/jspenguin2017/uBlockProtector/issues/1097) with a developer of a popular extension that did this (Hugo Xu of Nano Defeneder). 

That extension didn't detect automatically that we were checking for ad blocking, but worked by including a rule specifically targetted at our blockads.fivefilters.org site. 

It's somewhat surprising to me that someone with his views then went and cavalierly sold his extension to anonymous developers [putting at risk his 200,000 users](https://www.ghacks.net/2020/10/16/time-to-remove-nano-adblocker-and-defender-from-your-browsers-except-firefox/). The extension was then pulled by Google for being unsafe.
