### ISSUE TITLE
URL shortener: Something went wrong

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [fivefilters/block-ads#15]
When I enters a link and hit shortern, it jumps to a page with plain text. The text said: `Sorry, something went wrong. :(`

**Comment by fivefilters** [comment]
Sorry about that. We were using tinyurl.com to shorten URLs users entered into blockads.fivefilters.org. They appear to have blocked this (perhaps it was being abused), so we're removing the URL shortening feature.
