### ISSUE TITLE
FYI: when linking wiki pages use #wiki-wrapper

### ISSUE THREAD

**Issue by ghost** [fivefilters/block-ads#4]
I noticed you linked to `#wrapper` on hackernews: https://github.com/fivefilters/block-ads/wiki/There-are-no-acceptable-ads#wrapper 

The actual id you want is `wiki-wrapper`: https://github.com/fivefilters/block-ads/wiki/There-are-no-acceptable-ads#wiki-wrapper 

For some reason Github re-writes `#wiki-wrapper` to `#wrapper` on page load. I have no idea why.

**Comment by fivefilters** [comment]
I don't know why either! I thought I was linking to the correct section, but seems not.

**Comment by ghost** [comment]
I sent them a bug report about it, hopefully they can get it fixed.
